set term=builtin_ansi
syn on
set autoindent
colorscheme koehler
set tabstop=4
set expandtab
set shiftwidth=4
set encoding=utf8
set number
set ruler
set bs=2
set nocp
set ignorecase
set smartcase
set hlsearch
set incsearch
set history=1000
set undolevels=1000
set title
set visualbell
set noerrorbells
set foldmethod=marker
set foldmarker=/*,*/
set copyindent

""" Remap :W to :w
cnoreabbrev <expr> W ((getcmdtype() is# ':' && getcmdline() is# 'W')?('w'):('W'))
