set term=builtin_ansi
syn on
set autoindent

colorscheme koehler

set tabstop=4
set noexpandtab
set shiftwidth=4
set encoding=utf8
set number
set ruler
set bs=2
set nocp
set ignorecase
set smartcase
set hlsearch
set incsearch
set history=1000
set undolevels=1000
set title
set visualbell
set noerrorbells
set foldmethod=marker
set foldmarker=/*,*/
set copyindent
set exrc
set secure
set list
set listchars=tab:>-,trail:_,extends:#,nbsp:_

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Bundle 'scrooloose/nerdtree'
Bundle 'tpope/vim-surround'
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle 'garbas/vim-snipmate'
Bundle 'groenewege/vim-less'
call vundle#end()

autocmd vimenter * NERDTree " Autoopen NERDtree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif " Exit if only NERDtree present

filetype plugin indent on
autocmd filetype python set expandtab
autocmd filetype ruby set expandtab
autocmd BufRead,BufNewFile *.less set syntax=less

" Remap :W to :w
cnoreabbrev <expr> W ((getcmdtype() is# ':' && getcmdline() is# 'W')?('w'):('W'))

" Unbind the cursor keys in insert, normal and visual modes.
for prefix in ['i', 'n', 'v']
  for key in ['<Up>', '<Down>', '<Left>', '<Right>']
    exe prefix . "noremap " . key . " <Nop>"
  endfor
endfor

" Map ctrl+n to toggle NERDtree
map <C-n> :NERDTreeToggle<CR>

if has("gui_running")
	colorscheme smyck
end

" Store swap files in fixed location, not current directory.
set dir=~/.vimswap//,.
